# Generated by Django 5.1.2 on 2024-10-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_bio_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='Организатор'),
        ),
    ]
