# Generated by Django 5.1.2 on 2024-11-03 05:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_images/default.jpg', upload_to=users.models.user_directory_path, verbose_name='Картинка пролфиля'),
        ),
    ]
