# Generated by Django 5.1.2 on 2024-11-03 10:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_images/profile_images/default.jpg', upload_to=users.models.user_directory_path, verbose_name='Картинка пролфиля'),
        ),
    ]
