# Generated by Django 4.2.16 on 2024-10-26 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_bio_alter_userprofile_first_name_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[('5', '5 - Отлично'), ('4', '4 - Хорошо'), ('3', '3 - Неплохо'), ('2', '2 - Плохо'), ('1', '1 - Очень плохо')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='Удаленный пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.userprofile', verbose_name='Пользователь'),
        ),
    ]
