# Generated by Django 5.1.2 on 2024-10-28 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(5, '5 - Отлично'), (4, '4 - Хорошо'), (3, '3 - Неплохо'), (2, '2 - Плохо'), (1, '1 - Очень плохо')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
