# Generated by Django 5.1.2 on 2024-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='event_images/%Y/%m/%d', verbose_name='Картинка мероприятия'),
        ),
    ]
