# Generated by Django 5.1.2 on 2024-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='media/event_images/%Y/%m/%d/', verbose_name='Картинка мероприятия'),
        ),
    ]
