# Generated by Django 4.2.16 on 2024-10-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Картинка мероприятия'),
        ),
    ]
