# Generated by Django 4.2.16 on 2024-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Подготовка'), (2, 'В процессе'), (3, 'Завершен'), (4, 'Отменен')], default=1, verbose_name='Статус мероприятия'),
        ),
    ]
